### ISSUE TITLE
Any documentation on tuning parameters?

### ISSUE THREAD

**Issue by Schmidtbit** [jrmontag/STLDecompose#14]
I know that you can tune the model in the r package, but how can I tune it in python?

-Thanks!

**Comment by jrmontag** [comment]
Hi @Schmidtbit, thanks for opening an issue. Can you point me to some documentation of the type of tuning that you're seeking (or that the R version supports)?

**Comment by Schmidtbit** [comment]
I found this [link](https://www.rdocumentation.org/packages/stats/versions/3.5.3/topics/stl) to the R documentation for STL. If I want to change `s.window` or `l.window` parameters can I do that with this package?

**Comment by jrmontag** [comment]
From my read of those docs, there is not a direct correspondence from between those R parameters and the ones available in this library. I think the primary reason is that the implementations are fundamentally different - though working toward similar outcomes. 

The two tunable parameters in [this implementation](https://github.com/jrmontag/STLDecompose/blob/master/stldecompose/stl.py#L9) are `lo_frac` and `lo_delta` which are passed through directly to [the underlying `lowess()` function](http://www.statsmodels.org/devel/generated/statsmodels.nonparametric.smoothers_lowess.lowess.html) in `statsmodels` (in the underlying function, they don't have the `lo_` prefix). 

Perhaps experimenting with those two parameters will help you tune the fit for your use case.

**Comment by Schmidtbit** [comment]
Thanks for your help. I will try adjusting those parameters to see if I can improve the outcome.
