### ISSUE TITLE
import from statsmodels '_maybe_get_pandas_wrapper_freq' not working

### ISSUE THREAD

**Issue by chaizeg** [jrmontag/STLDecompose#18]
Hello,

In the latest version of the stldecompose library, the import in line 5 of stl.py doesn't work with the  latest versions of  statsmodels as that function has already been deleted in a commit done back in July 2019

**Comment by yuming-p** [comment]
Hi,

May i ask how did you fix this problem?
i could not find a corresponding new function name that works.
Thanks in advance.

**Comment by jrmontag** [comment]
@whiskypizza try the approach described here: https://github.com/jrmontag/STLDecompose/issues/17

**Comment by yuming-p** [comment]
> @whiskypizza try the approach described here: #17

Yes it worked. Thx!
