### ISSUE TITLE
STL no longer works due to change in statsmodels

### ISSUE THREAD

**Issue by omri374** [jrmontag/STLDecompose#19]
stl.py references `_maybe_get_pandas_wrapper_freq` which no longer exists in current and future versions of statsmodels.

**Comment by jrmontag** [comment]
@omri374 It's always a good idea to search the existing issues on a repo - for example, [this one](https://github.com/jrmontag/STLDecompose/issues/18).

**Comment by omri374** [comment]
Hi @jrmontag, thanks for the reference, but why is this issue closed? 

The package is broken for anyone new using it as it does not specify the `statsmodels` version it expects and is not compatible with current versions. 

Issue #18 should be open IMHO for reference. Even specifying `statsmodels==0.10.2` in the setup.py would be a valid fix for the issue.

**Comment by jrmontag** [comment]
@omri374 I agree that it would be helpful to leave one of these open as a reference. Thanks for the tip - I'll re-open the [earlier one](https://github.com/jrmontag/STLDecompose/issues/17).
