### ISSUE TITLE
Misleading title - this is not an implementation of the classical STL procedure

### ISSUE THREAD

**Issue by NoamGit** [jrmontag/STLDecompose#9]
The procedure described in [Cleveland et al. 1990](https://www.researchgate.net/publication/235709689_STL_A_Seasonal-Trend_Decomposition_Procedure_Based_on_Loess) is very different from the code in `stl.py`. I would recommend changing the name to `seasonal_decompose` instead of STL. It is very misleading...

**Comment by jrmontag** [comment]
Thanks for the feedback. I'll consider a modification.
